# Generated by Django 4.1.4 on 2023-04-05 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='status',
            field=models.BooleanField(blank=True, default=False, help_text='0-show,1-Hidden'),
        ),
    ]
