# Generated by Django 4.1.4 on 2023-04-27 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='guest_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_guest',
            field=models.BooleanField(default=False),
        ),
    ]
