# Generated by Django 4.1.4 on 2023-04-12 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_alter_orders_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
