# Generated by Django 4.1.4 on 2023-04-13 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_orders_cancelled'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaddress',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
