# Generated by Django 4.1.4 on 2023-05-04 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0012_return'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordereditems',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Out For Shipping', 'Out For Shipping'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Return Requested', 'Return Requested'), ('Return Approved', 'Return Approved')], default='Pending', max_length=150),
        ),
    ]
