# Generated by Django 4.1.4 on 2023-05-04 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0013_ordereditems_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='min_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Out For Shipping', 'Out For Shipping'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Return', 'Return'), ('ReturnApproved', 'ReturnApproved')], default='Pending', max_length=150),
        ),
    ]
