# Generated by Django 4.1.4 on 2023-05-02 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0002_banner_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='description',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='heading',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
