# Generated by Django 4.1.4 on 2023-05-05 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0003_banner_description_banner_heading'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
